pr:
  branches:
    include:
      - main

trigger:
  branches:
    include:
      - main

resources:
  - repo: self

stages:
  - stage: BlazorLore
    displayName: Build, pack and push BlazorLore
    jobs:
      - job: BlazorLore
        displayName: Build, pack and push BlazorLore
        pool:
          name: Azure Pipelines
        steps:
          # Nerdbank.GitVersioning requires a full clone to work correctly
          - checkout: self
            fetchDepth: "0"
            displayName: "Checkout source code (full clone, not shallow clone)"
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '9.x'
              installationPath: $(Agent.ToolsDirectory)/dotnet
            displayName: 'Install .NET SDK'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'pack'
              packagesToPack: '**/BlazorLore.Format.Cli.csproj'
              includesymbols: true
              includesource: true
            displayName: "Pack NuGet packages"
          - task: NuGetToolInstaller@1
            displayName: "Install NuGet"
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
          - task: NuGetAuthenticate@1
            displayName: "Authenticate to Azure DevOps NuGet feed"
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
          - script: |
              dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source https://pkgs.dev.azure.com/caputenergy/caput-azure/_packaging/cap/nuget/v3/index.json --api-key AzureDevOps --skip-duplicate
            displayName: "Push to Azure DevOps NuGet Feed"
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
